version: "3.8"
services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shubham
      MYSQL_DATABASE: spring
      MYSQL_USER: shubham
      MYSQL_PASSWORD: shubham
      ports: 3306

